
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rentt
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    // Conta
    Conta conta = new Conta("", "", 0.0);
    
    //Conta corrente
    private ContaCorrente contaCorrente;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_NumeroConta = new javax.swing.JTextField();
        jTextField_Agencia = new javax.swing.JTextField();
        jButton_Acessar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_Saldo = new javax.swing.JLabel();
        jCheckBox_CC = new javax.swing.JCheckBox();
        jButton_Depositar = new javax.swing.JButton();
        jButton_Sacar = new javax.swing.JButton();
        jCheckBox_CP = new javax.swing.JCheckBox();
        jButton_AplicarRendimento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("BANCO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Conta");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Agência");

        jTextField_NumeroConta.addActionListener(this::jTextField_NumeroContaActionPerformed);

        jButton_Acessar.setText("Acessar");
        jButton_Acessar.addActionListener(this::jButton_AcessarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(156, 156, 156))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Acessar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField_NumeroConta)
                        .addComponent(jTextField_Agencia, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_NumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Agencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton_Acessar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Saldo");

        jLabel_Saldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Saldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Saldo.setText("0.00");

        jCheckBox_CC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox_CC.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_CC.setText("Conta Corrente");
        jCheckBox_CC.addActionListener(this::jCheckBox_CCActionPerformed);

        jButton_Depositar.setText("Depositar");
        jButton_Depositar.setEnabled(false);
        jButton_Depositar.addActionListener(this::jButton_DepositarActionPerformed);

        jButton_Sacar.setText("Sacar");
        jButton_Sacar.setEnabled(false);

        jCheckBox_CP.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_CP.setText("Conta Poupança");
        jCheckBox_CP.addActionListener(this::jCheckBox_CPActionPerformed);

        jButton_AplicarRendimento.setText("Aplicar Rendimento");
        jButton_AplicarRendimento.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Saldo))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox_CC)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jButton_Depositar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton_Sacar))
                        .addComponent(jCheckBox_CP)
                        .addComponent(jButton_AplicarRendimento)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_Saldo))
                .addGap(42, 42, 42)
                .addComponent(jCheckBox_CC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Depositar)
                    .addComponent(jButton_Sacar))
                .addGap(33, 33, 33)
                .addComponent(jCheckBox_CP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_AplicarRendimento)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NumeroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NumeroContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NumeroContaActionPerformed

    private void jButton_AcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AcessarActionPerformed
        // TODO add your handling code here:
        
        conta.setNumeroConta(jTextField_NumeroConta.getText());
        conta.setAgencia(jTextField_Agencia.getText());
        jLabel_Saldo.setText("0.00");
        
        JOptionPane.showMessageDialog(null, conta.toString());
    }//GEN-LAST:event_jButton_AcessarActionPerformed

    private void jCheckBox_CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_CCActionPerformed
        // TODO add your handling code here:
        
        if (jCheckBox_CC.isSelected()){
            jButton_Depositar.setEnabled(true);
            jButton_Sacar.setEnabled(true);
            jCheckBox_CP.setEnabled(false);
        } else {
            jButton_Depositar.setEnabled(false);
            jButton_Sacar.setEnabled(false);
            jCheckBox_CP.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox_CCActionPerformed

    private void jCheckBox_CPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_CPActionPerformed
        // TODO add your handling code here:
        
        if(jCheckBox_CP.isSelected()){
            jButton_AplicarRendimento.setEnabled(true);
            jCheckBox_CC.setEnabled(false);
        } else {
            jButton_AplicarRendimento.setEnabled(false);
            jCheckBox_CC.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox_CPActionPerformed

    private void jButton_DepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DepositarActionPerformed
        // TODO add your handling code here:
        
        String valorDepositoText = JOptionPane.showInputDialog(null, "Valor: ");
        Double valorDeposito = Double.parseDouble(valorDepositoText);
        
        contaCorrente.depositar(valorDeposito);
        
    }//GEN-LAST:event_jButton_DepositarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Acessar;
    private javax.swing.JButton jButton_AplicarRendimento;
    private javax.swing.JButton jButton_Depositar;
    private javax.swing.JButton jButton_Sacar;
    private javax.swing.JCheckBox jCheckBox_CC;
    private javax.swing.JCheckBox jCheckBox_CP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Saldo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField_Agencia;
    private javax.swing.JTextField jTextField_NumeroConta;
    // End of variables declaration//GEN-END:variables
}
